//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUDelivery
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.DetallePedido = new HashSet<DetallePedido>();
        }

        [ScaffoldColumn(false)]
        public int idProducto { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "El nombre es requerido"), MaxLength(50)]
        [Display(Name = "Nombre")]
        public string nombre { get; set; }

        /*[Required(ErrorMessage = "The Salary is required.")]
        [Range(0.00, 100.00)]*/
        [DisplayFormat(DataFormatString = "{0:C}")]
        public Nullable<decimal> precio { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "El comentario sobre el producto es necesario"), MaxLength(75)]
        [Display(Name = "Comentario")]
        public string comentario { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "El estado es requerido"), MaxLength(75)]
        [Display(Name = "Estado")]
        public string estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePedido> DetallePedido { get; set; }
    }
}
