//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUDelivery
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Pedido = new HashSet<Pedido>();
        }

        [ScaffoldColumn(false)]
        public int idUsuario { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "El nombre es requerido"), MaxLength(50)]
        [Display(Name = "Nombre")]
        public string nombre { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "El apellido es requerido"), MaxLength(50)]
        [Display(Name = "Apellido")]
        public string apellido { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "La cédula es requerida"), MaxLength(15)]
        [Display(Name = "Cédula")]
        public string cedula { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "El télefono es requerido"), MaxLength(15)]
        [Display(Name = "Número de teléfono")]
        public string telefono { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "La dirección es requerida"), MaxLength(50)]
        [Display(Name = "Dirección")]
        public string direccion { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "La contraseña es requerida"), MaxLength(15)]
        [Display(Name = "Contraseña")]
        public string contrasena { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Es requerido un usuario."), MaxLength(15)]
        [Display(Name = "Usuario")]
        public string usuario1 { get; set; }

        [DataType(DataType.Text)]
        [Required(ErrorMessage = "El rol es requerido"), MaxLength(15)]
        [Display(Name = "ROL")]
        public string rol { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedido> Pedido { get; set; }
    }
}
